## YAML Template.
---
security:
     jwt:
         secret-key: keydeencriptacion
spring:
    application:
        name: Ensayos Servidor
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_ensayos
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true